#!/bin/bash
#
# Send messages via https://pushover.net/
#
#      /__/\         /  /\         /__/\
#      \  \:\       /  /::\       |  |::\
#       \__\:\     /  /:/\:\      |  |:|:\
#   ___ /  /::\   /  /:/~/::\   __|__|:|\:\
#  /__/\  /:/\:\ /__/:/ /:/\:\ /__/::::| \:\
#  \  \:\/:/__\/ \  \:\/:/__\/ \  \:\~~\__\/
#   \  \::/       \  \::/       \  \:\
#    \  \:\        \  \:\        \  \:\
#     \  \:\        \  \:\        \  \:\
#      \__\/         \__\/         \__\/
#

pushover_token=af6g31xkk32szf64qcii754r1oxcub
pushover_user=u84xo9g5yygp4omt963hfgjku2v7q5

# message is arguments if supplied else relies on stdin as message
if [ "$#" -gt 0 ]
then
    msg="$@"
else
    msg="$(cat)"
fi

curl \
    -s \
    -F "token=$pushover_token" \
    -F "user=$pushover_user" \
    -F "message=$msg" \
    https://api.pushover.net/1/messages.json \
    > /dev/null
